@baseUrl = http://localhost:5000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMTM4ODc5MWEtOGUzZC00OWMyLTlmMTktNjQ1NTU3MjkxZmFhIiwicm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNzY1NzIyMjMyfQ.C3OzdO7BtN9QEL67yEnFwKc5YmAXp0oKrgl_RMlrOeA
### ==========================================
### 1. TEST ĐĂNG KÝ (REGISTER)
### ==========================================
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "full_name": "Nguyen Van Hieu",
  "email": "hieutest12@gmail.com",
  "password": "password123",
  "phone_number": "0987654321"
}

### ==========================================
### 2. TEST ĐĂNG NHẬP (LOGIN)
### ==========================================
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "hieutest12@gmail.com",
  "password": "password123"
}

### ==========================================
### 3. TEST LỖI VALIDATION (Thử nhập thiếu SĐT)
### ==========================================
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "full_name": "User Loi",
  "email": "loi@gmail.com",
  "password": "123"
}

### ==========================================

GET {{baseUrl}}/users/profile
Authorization: Bearer {{token}}

### ==========================================
### 4. CẬP NHẬT HỒ SƠ (UPDATE PROFILE)
### ==========================================
PUT {{baseUrl}}/users/profile
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "full_name": "Nguyen Van A (Da Sua)",
  "gender": "male",
  "birth_date": "2000-10-20",
  "phone_number": "0999888777"
}

### ==========================================
### 6. ĐỔI MẬT KHẨU (CHANGE PASSWORD)
### ==========================================
PUT {{baseUrl}}/users/change-password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "current_password": "password123",
  "new_password": "newpassword456",
  "confirm_password": "newpassword456"
}

### ==========================================
### 8. LẤY DANH SÁCH ĐỊA CHỈ (GET)
### ==========================================
GET {{baseUrl}}/addresses
Authorization: Bearer {{token}}


### ==========================================
### 10. THÊM ĐỊA CHỈ MỚI (POST)
### ==========================================
POST {{baseUrl}}/addresses
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "recipient_name": "Nguyen Van A",
  "phone": "0912345678",
  "street": "So 10 Ngo 12",
  "ward": "Lang Thuong",
  "district": "Dong Da",
  "city": "Ha Noi",
  "is_default": false
}

### Thêm một địa chỉ nữa (để test danh sách)
POST {{baseUrl}}/addresses
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "recipient_name": "Tran Van C",
  "phone": "0987654321",
  "street": "So 123 Duong Lang",
  "ward": "Lang Ha",
  "district": "Dong Da",
  "city": "Ha Noi",
  "is_default": true
}


### ==========================================
### 11. SỬA ĐỊA CHỈ (PUT)
### ==========================================
# ⚠️ HƯỚNG DẪN:
# 1. Chạy API "Lấy danh sách" ở trên.
# 2. Copy một cái "address_id" bất kỳ (ví dụ: "a1b2c3d4...").
# 3. Thay thế vào chỗ <ID_DIA_CHI> ở link bên dưới.
@addressId =87a822e7-4612-4912-8a44-021610aa2765
PUT {{baseUrl}}/addresses/{{addressId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "recipient_name": "Nguyen uuu (Da Sua)",
  "phone": "0999888777",
  "street": "So 1330 Ngo 12 (Sua)",
  "ward": "Lang Thuong",
  "district": "Dong Da",
  "city": "Ha Noi",
  "is_default": false
}


### ==========================================
### 12. XÓA ĐỊA CHỈ (DELETE)
### ==========================================
# ⚠️ HƯỚNG DẪN: Thay ID cần xóa vào chỗ <ID_DIA_CHI>

DELETE {{baseUrl}}/addresses/{{addressId}}
Authorization: Bearer {{token}}

### ==========================================
### 13. TÌM KIẾM SẢN PHẨM (SEARCH)
### ==========================================

# Test 1: Lấy tất cả (sẽ ra 2 sản phẩm)
POST {{baseUrl}}/products/search
Content-Type: application/json

{
  "page": 1,
  "limit": 10
}

### Test 2: Tìm theo tên "Nike" (sẽ ra 1 sản phẩm)
POST {{baseUrl}}/products/search
Content-Type: application/json

{
}

### Test 3: Lọc theo giá (từ 4 triệu trở lên -> ra Adidas)
POST {{baseUrl}}/products/search
Content-Type: application/json

{
  "min_price": 4000000
}

### ==========================================
### 14. LẤY DỮ LIỆU BỘ LỌC (FULL OPTIONS)
### ==========================================
GET {{baseUrl}}/products/filters


### ==========================================
### 15. LẤY TOP BÁN CHẠY (TRENDING)
### ==========================================
GET {{baseUrl}}/products/trending?limit=5

### ==========================================
### 16. LẤY CHI TIẾT SẢN PHẨM (DETAIL)
### ==========================================

# Bước 1: Gọi search để lấy ID trước (nếu quên)
POST {{baseUrl}}/products/search
Content-Type: application/json

{
}
###

# Bước 2: Thay ID sản phẩm vào chỗ <ID_SAN_PHAM>
GET {{baseUrl}}/products/c2dd3344-ee55-66ff-8899-aabbccddee02

### ==========================================
### 17. THÊM VÀO GIỎ HÀNG
### ==========================================
POST {{baseUrl}}/cart/add
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "variant_id": "d4ee5566-ff77-8899-00aa-bbccddeeff03",
  "quantity": 1
}

### ==========================================
### 18. XEM GIỎ HÀNG (GET CART)
### ==========================================
GET {{baseUrl}}/cart
Authorization: Bearer {{token}}